{
 "title": "NGINX Метрики",
 "description": "Official dashboard for NGINX Prometheus exporter",
 "tags": [
  "nginx",
  "prometheus",
  "nginx prometheus exporter"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "vm", "label": "Виртуальная машина", "query": { "query": "label_values(up, vm)" } }
  ]
 },
 "panels": [
  { "title": "Статус", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NGINX статус",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{vm=~\"${vm:regex}\"}"
    }
   ]
  },
  { "title": "Метрики", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Обработанные подключения",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(nginx_connections_accepted{vm=~\"${vm:regex}\"}[5m])",
     "legendFormat": "{{instance}} принято"
    },
    {
     "expr": "irate(nginx_connections_handled{vm=~\"${vm:regex}\"}[5m])",
     "legendFormat": "{{instance}} обработано"
    }
   ]
  },
  {
   "title": "Активные подключения",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nginx_connections_active{vm=~\"${vm:regex}\"}",
     "legendFormat": "{{instance}} активных"
    },
    {
     "expr": "nginx_connections_reading{vm=~\"${vm:regex}\"}",
     "legendFormat": "{{instance}} читает"
    },
    {
     "expr": "nginx_connections_waiting{vm=~\"${vm:regex}\"}",
     "legendFormat": "{{instance}} ожидает"
    },
    {
     "expr": "nginx_connections_writing{vm=~\"${vm:regex}\"}",
     "legendFormat": "{{instance}} пишет"
    }
   ]
  },
  {
   "title": "Всего запросов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(nginx_http_requests_total{vm=~\"${vm:regex}\"}[5m])",
     "legendFormat": "{{instance}} всего запросов"
    }
   ]
  }
 ]
}