-- Demo data for the HTTP DB gateway (POST /v1/sql/oracle/query).
-- gvenzl/oracle-xe runs *.sql scripts as SYS AS SYSDBA in CDB$ROOT, so switch
-- to the default pluggable database before touching the app_user schema.
ALTER SESSION SET CONTAINER = XEPDB1;

CREATE TABLE app_user.demo_messages (
  id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message    VARCHAR2(512) NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

INSERT INTO app_user.demo_messages (message) VALUES ('Hello from Oracle DB gateway');
INSERT INTO app_user.demo_messages (message) VALUES ('DB gateway works over NATS');
COMMIT;
